#!/usr/bin/env python3
"""
Generate a compact context digest for Claude sessions.

Instead of Claude reading 10+ files at session start, this script produces
a single DIGEST.md with all essential info compressed.

Usage:
    python context_digest.py              # generates DIGEST.md
    python context_digest.py -o custom.md # custom output path

Saves ~20-25k tokens per session.
"""
import argparse
import sys
from pathlib import Path

import yaml


def load_config_safe(path: Path) -> dict | None:
    """Load a YAML config, return None on error."""
    try:
        with open(path, encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"  WARNING: Could not load {path}: {e}", file=sys.stderr)
        return None


def parse_adn_file(path: Path) -> dict:
    """Extract key info from an adn_phonetique.txt file."""
    info = {"attacks": [], "endings_m": [], "endings_f": [], "forbidden": [], "vowels": ""}
    if not path.exists():
        return info

    current_section = None
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            upper = line.upper()

            if "ATTAQUE" in upper or "ATTACK" in upper:
                current_section = "attacks"
            elif "TERMINAISON" in upper and ("MASC" in upper or " M " in upper or "MALE" in upper):
                current_section = "endings_m"
            elif "TERMINAISON" in upper and ("FEM" in upper or " F " in upper):
                current_section = "endings_f"
            elif "INTERDIT" in upper or "FORBIDDEN" in upper or "RESERVE" in upper:
                current_section = "forbidden"
            elif "VOYELLE" in upper or "VOWEL" in upper:
                current_section = "vowels"
            elif line.startswith("#") or line.startswith("="):
                continue
            elif line and current_section:
                # Extract the first token (the phoneme/marker)
                token = line.split()[0].strip("-,;:()[]")
                if token and len(token) <= 15:
                    if current_section == "vowels":
                        info["vowels"] += " " + token
                    else:
                        info[current_section].append(token)

    return info


def parse_status_file(path: Path) -> str:
    """Extract pipeline stage from STATUS.md."""
    if not path.exists():
        return "no STATUS.md"
    with open(path, encoding="utf-8") as f:
        content = f.read()

    # Find the pipeline section and count completed steps
    completed = content.count("[x]")
    total = content.count("[x]") + content.count("[ ]")

    # Find "Prochaine action" or "Next"
    next_action = ""
    for line in content.split("\n"):
        if "prochaine" in line.lower() or "next" in line.lower():
            next_action = line.strip().lstrip("-# ")
            break

    return f"Etape {completed}/{total}" + (f" — {next_action}" if next_action else "")


def flatten_names(custom: dict | list | None) -> list[str]:
    """Flatten custom_names dict or list to a flat list."""
    if custom is None:
        return []
    if isinstance(custom, list):
        return list(custom)
    names = []
    for cat_names in custom.values():
        if isinstance(cat_names, list):
            names.extend(cat_names)
    return names


def extract_prefixes(names: list[str], n: int = 3) -> list[str]:
    """Extract the N most common prefixes (first 3 chars) from name list."""
    from collections import Counter
    prefixes = Counter()
    for name in names:
        if len(name) >= 3:
            prefixes[name[:3]] += 1
    return [p for p, _ in prefixes.most_common(n)]


def generate_digest(root: Path) -> str:
    """Generate the full digest content."""
    names_dir = root / "names"
    lines = []

    lines.append("# DIGEST — Etra Names & Cultures")
    lines.append("# Auto-generated by context_digest.py — do NOT edit manually")
    lines.append("")

    # === 1. Pipeline status ===
    lines.append("## Pipeline Status")
    lines.append("")
    lines.append("| Langue | Etape | M | F | Dyn | Low | Dialectes |")
    lines.append("|--------|-------|---|---|-----|-----|-----------|")

    lang_data = {}
    configs = sorted(names_dir.glob("*/config.yaml")) if names_dir.exists() else []

    for config_path in configs:
        lang_name = config_path.parent.name
        cfg = load_config_safe(config_path)
        if not cfg:
            continue

        custom = cfg.get("custom_names", {})
        n_m = len(flatten_names(custom.get("male")))
        n_f = len(flatten_names(custom.get("female")))
        n_dyn = len(custom.get("dynasties", []))
        n_low = len(custom.get("lowborn", []))
        n_dialects = len(cfg.get("dialects", []))

        status_path = config_path.parent / "STATUS.md"
        status = parse_status_file(status_path)

        lines.append(f"| {lang_name} | {status} | {n_m} | {n_f} | {n_dyn} | {n_low} | {n_dialects} |")

        lang_data[lang_name] = {
            "cfg": cfg,
            "male": flatten_names(custom.get("male")),
            "female": flatten_names(custom.get("female")),
            "dynasties": custom.get("dynasties", []),
            "lowborn": custom.get("lowborn", []),
        }

    # Also check for languages without config.yaml
    if names_dir.exists():
        for lang_dir in sorted(names_dir.iterdir()):
            if lang_dir.is_dir() and lang_dir.name not in lang_data:
                status_path = lang_dir / "STATUS.md"
                status = parse_status_file(status_path)
                lines.append(f"| {lang_dir.name} | {status} | ? | ? | ? | ? | ? |")

    lines.append("")

    # === 2. Non-recouvrement matrix ===
    lines.append("## Matrice de non-recouvrement (prefixes exclusifs)")
    lines.append("")
    lines.append("| Langue | Prefixes M (top 10) | Prefixes F (top 10) | Terminaisons M exclusives | Terminaisons F exclusives |")
    lines.append("|--------|--------------------|--------------------|--------------------------|--------------------------|")

    for lang_name, data in lang_data.items():
        # Extract prefixes from names
        m_prefixes = extract_prefixes(data["male"], 10)
        f_prefixes = extract_prefixes(data["female"], 10)

        # Try to get exclusive markers from ADN file
        adn_path = names_dir / lang_name / "adn_phonetique.txt"
        adn = parse_adn_file(adn_path)

        endings_m = ", ".join(adn["endings_m"][:8]) if adn["endings_m"] else "—"
        endings_f = ", ".join(adn["endings_f"][:8]) if adn["endings_f"] else "—"

        lines.append(f"| {lang_name} | {', '.join(m_prefixes)} | {', '.join(f_prefixes)} | {endings_m} | {endings_f} |")

    lines.append("")

    # === 3. Reserved markers quick-ref ===
    lines.append("## Marqueurs reserves (quick-ref)")
    lines.append("")
    lines.append("```")
    lines.append("Ardrainic  : -ain/-eval, Gal-/Thib-/Lanc-/Perc-")
    lines.append("Torrentian : -wald/-mar/-mund, Wulf-/Sig-/Grim-/Skor-/Drak-")
    lines.append("Armonorican: Ll-/Rh-/Gw-, -wyn/-wen/-ydd")
    lines.append("Sordrenic  : -tz/-enc/-esc, Esc-/Rai-/Oiss-")
    lines.append("Moran      : -us/-ius/-ox/-ex, Aeter-/Mort-/Nex-")
    lines.append("Hravevi    : -oush/-azd/-avan, Tig-/Hov-/Art-")
    lines.append("Vulgar Mor.: -avel/-oren/-iant, Aur-/Val-/Corv-")
    lines.append("```")
    lines.append("")

    # === 4. Dialect assignments ===
    lines.append("## Dialectes par langue")
    lines.append("")
    for lang_name, data in lang_data.items():
        cfg = data["cfg"]
        dialects = cfg.get("dialects", [])
        if dialects:
            dialect_ids = [d["id"] for d in dialects]
            default = cfg.get("default_dialect_id", cfg["language_id"])
            lines.append(f"**{lang_name}** ({len(dialects)} dialectes, default={default})")
            for did in dialect_ids:
                lines.append(f"  - {did}")
            lines.append("")

    # === 5. Culture → dialect mapping ===
    lines.append("## Cultures → Dialectes")
    lines.append("")
    for lang_name, data in lang_data.items():
        cfg = data["cfg"]
        cultures = cfg.get("cultures", [])
        if cultures:
            lines.append(f"**{lang_name}**")
            for c in cultures:
                lines.append(f"  {c['id']} → {c['dialect']}")
            lines.append("")

    # === 6. Fichiers existants par langue ===
    lines.append("## Fichiers par langue")
    lines.append("")
    if names_dir.exists():
        for lang_dir in sorted(names_dir.iterdir()):
            if lang_dir.is_dir():
                files = [f.name for f in sorted(lang_dir.iterdir()) if f.is_file()]
                lines.append(f"**{lang_dir.name}/** : {', '.join(files)}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate compact context digest for Claude sessions.")
    parser.add_argument("-o", "--output", default="DIGEST.md", help="Output file path (default: DIGEST.md)")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent
    digest = generate_digest(root)

    output_path = Path(args.output)
    output_path.write_text(digest, encoding="utf-8")
    print(f"Digest written to {output_path} ({len(digest)} chars)")


if __name__ == "__main__":
    main()
