#!/usr/bin/env python3
"""
Generate EU5/Etra fantasy title translations with game rule toggle.

Reads title translations from YAML config and generates:
  1. Game rule file (pre-game toggle: English / Fantasy)
  2. Customizable localization (dynamic per ruler culture)
  3. Localization YML (all translated names)

Output goes to overrides/ so generate_mod.py --all picks it up automatically.

Usage:
    python generate_titles.py                    # generate from titles/config.yaml
    python generate_titles.py titles/custom.yaml # use specific config
    python generate_titles.py --list             # show translation status
    python generate_titles.py --audit            # find English names needing translation

Requires: PyYAML (pip install pyyaml)
"""
import argparse
import re
import sys
from pathlib import Path

import yaml


SCRIPT_DIR = Path(__file__).resolve().parent

# Countries file from the Etra mod (for --audit)
ETRA_MOD = Path(r"C:\Program Files (x86)\Steam\steamapps\workshop\content\3450310\3619896881")
COUNTRY_NAMES_FILE = ETRA_MOD / "main_menu" / "localization" / "english" / "etra_country_names_l_english.yml"
COUNTRY_DEFS_FILE = ETRA_MOD / "in_game" / "setup" / "countries" / "_default.txt"


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(path: Path) -> dict:
    """Load and validate title translation config."""
    with open(path, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    if not cfg.get("titles"):
        cfg["titles"] = {}

    # Validate translations
    for tag, data in cfg.get("titles", {}).items():
        if not isinstance(data, dict):
            print(f"WARNING: Invalid entry for {tag}, skipping", file=sys.stderr)
            continue
        if "translations" not in data or not data["translations"]:
            print(f"WARNING: {tag} has no translations", file=sys.stderr)

    return cfg


# ---------------------------------------------------------------------------
# Generator: Game Rule
# ---------------------------------------------------------------------------

def generate_game_rule(cfg: dict) -> str:
    """Generate game_rules .txt content."""
    gr = cfg.get("game_rule", {})
    key = gr.get("key", "etra_title_names")
    default = gr.get("default", "fantasy")
    default_setting = f"etra_names_{default}"

    lines = [
        "# Etra: Names & Cultures — Title name language toggle",
        "# Generated by generate_titles.py",
        "#",
        "# When set to Fantasy Languages, country names display in the",
        "# ruler's culture language instead of English.",
        "",
        f"{key} = {{",
        f"\tdefault = {default_setting}",
        "",
        "\tetra_names_english = {",
        "\t\tflag = flavour_rule",
        "\t}",
        "",
        "\tetra_names_fantasy = {",
        "\t\tflag = flavour_rule",
        "\t}",
        "}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: Customizable Localization
# ---------------------------------------------------------------------------

def lang_short(lang_id: str) -> str:
    """Convert language_id to short form for loc keys."""
    return lang_id.replace("_language", "")


def generate_custom_loc(cfg: dict) -> str:
    """Generate customizable_localization .txt content.

    For each title with translations, creates a scope that resolves
    the country name based on game rule + ruler culture.

    Resolution order (first match wins):
      1. Fantasy mode + ruler's specific language → that language's name
      2. Fantasy mode + no match → native language name
      3. English fallback
    """
    titles = cfg.get("titles", {})
    if not titles:
        return ""

    lines = [
        "# Etra: Names & Cultures — Dynamic title names",
        "# Generated by generate_titles.py",
        "#",
        "# Resolves country names based on game rule + ruler culture.",
        "# When game rule = Fantasy: uses ruler's culture language.",
        "# When game rule = English: uses base English name.",
        "",
    ]

    for tag, data in titles.items():
        if not isinstance(data, dict):
            continue
        translations = data.get("translations", {})
        native = data.get("native")
        if not translations:
            continue

        english = data.get("english", tag)
        lines.append(f"# {tag}: {english}")
        lines.append(f"{tag} = {{")
        lines.append("\ttype = country")

        # 1. Per-language triggers (most specific)
        for lang_id in translations:
            loc_key = f"{tag}_{lang_short(lang_id)}"
            lines.append("\ttext = {")
            lines.append(f"\t\tlocalization_key = {loc_key}")
            lines.append("\t\ttrigger = {")
            lines.append("\t\t\thas_game_rule = etra_names_fantasy")
            lines.append(f"\t\t\truler ?= {{ culture.language = language:{lang_id} }}")
            lines.append("\t\t}")
            lines.append("\t}")

        # 2. Native fallback (fantasy mode, ruler language not in translations)
        if native:
            native_key = f"{tag}_{lang_short(native)}"
            if native in translations:
                lines.append("\ttext = {")
                lines.append(f"\t\tlocalization_key = {native_key}")
                lines.append("\t\ttrigger = {")
                lines.append("\t\t\thas_game_rule = etra_names_fantasy")
                lines.append("\t\t}")
                lines.append("\t}")
            else:
                # Native language has no translation — use first available
                first_lang = next(iter(translations))
                fallback_key = f"{tag}_{lang_short(first_lang)}"
                lines.append("\ttext = {")
                lines.append(f"\t\tlocalization_key = {fallback_key}")
                lines.append("\t\ttrigger = {")
                lines.append("\t\t\thas_game_rule = etra_names_fantasy")
                lines.append("\t\t}")
                lines.append("\t}")

        # 3. English fallback
        lines.append("\ttext = {")
        lines.append(f"\t\tlocalization_key = {tag}")
        lines.append("\t\tfallback = yes")
        lines.append("\t}")

        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: Localization YML
# ---------------------------------------------------------------------------

def generate_localization(cfg: dict) -> str:
    """Generate localization .yml content with game rule labels + translations."""
    titles = cfg.get("titles", {})
    gr = cfg.get("game_rule", {})
    key = gr.get("key", "etra_title_names")
    desc_en = gr.get("desc_english", "Use English names for countries and titles")
    desc_fantasy = gr.get("desc_fantasy", "Use fantasy language names based on ruler's culture")
    label = gr.get("label", "Etra: Title Names")

    lines = [
        "# Etra: Names & Cultures — Title translation localization",
        "# Generated by generate_titles.py",
        "",
        "l_english:",
        "",
        " # --- GAME RULE ---",
        f' rule_{key}: "{label}"',
        f' setting_etra_names_english: "English"',
        f' setting_etra_names_english_desc: "{desc_en}"',
        f' setting_etra_names_fantasy: "Fantasy Languages"',
        f' setting_etra_names_fantasy_desc: "{desc_fantasy}"',
    ]

    if not titles:
        return "\n".join(lines) + "\n"

    lines.append("")
    lines.append(" # --- TITLE TRANSLATIONS ---")

    for tag, data in titles.items():
        if not isinstance(data, dict):
            continue
        translations = data.get("translations", {})
        english = data.get("english", tag)
        if not translations:
            continue

        lines.append(f" # {tag}: {english}")
        for lang_id, translated_name in translations.items():
            loc_key = f"{tag}_{lang_short(lang_id)}"
            # Escape quotes in names
            safe_name = translated_name.replace('"', '\\"')
            lines.append(f' {loc_key}: "{safe_name}"')
        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Audit: find English names needing translation
# ---------------------------------------------------------------------------

def parse_country_names(path: Path) -> dict[str, str]:
    """Parse etra_country_names_l_english.yml → {tag: name}."""
    names = {}
    if not path.exists():
        return names
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("l_english"):
                continue
            # Match: TAG: "Name" or TAG:0 "Name"
            m = re.match(r'^\s*(\w+?)(?::\d+)?\s*:\s*"(.+?)"', line)
            if m:
                tag, name = m.group(1), m.group(2)
                if not tag.endswith("_ADJ"):
                    names[tag] = name
    return names


def parse_country_cultures(path: Path) -> dict[str, str]:
    """Parse _default.txt → {tag: culture_definition} (line-by-line)."""
    cultures = {}
    if not path.exists():
        return cultures
    current_tag = None
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            m = re.match(r'^(\w+)\s*=\s*\{', line)
            if m:
                current_tag = m.group(1)
            cm = re.search(r'culture_definition\s*=\s*(\w+)', line)
            if cm and current_tag:
                cultures[current_tag] = cm.group(1)
    return cultures


def is_english_name(name: str) -> bool:
    """Heuristic: name contains English words (the, of, and, etc.)."""
    english_markers = [
        "The ", " the ", " of ", " and ", " in ",
        "Order", "Watch", "Daughters", "Sons", "Eagles",
        "Warriors", "Lions", "Sentinels", "Preservers",
        "Path", "Temple", "School", "Judge", "Fist",
        "Star", "Peak", "Bear", "Hawk", "Bell",
        "Crown", "Pale ", "Silent", "Radiant", "Exalted",
        "Little ", "Blue", "Green", "Drunken", "Final",
        "Ashes", "Heaven", "Virtuous", "Autumn",
    ]
    return any(marker in name for marker in english_markers)


def audit_titles(cfg: dict):
    """Find country names that look English and need translation."""
    country_names = parse_country_names(COUNTRY_NAMES_FILE)
    country_cultures = parse_country_cultures(COUNTRY_DEFS_FILE)
    existing = set(cfg.get("titles", {}).keys())

    if not country_names:
        print("ERROR: Could not read country names from Etra mod.", file=sys.stderr)
        print(f"  Expected: {COUNTRY_NAMES_FILE}", file=sys.stderr)
        return

    english_names = []
    for tag, name in sorted(country_names.items()):
        if tag in existing:
            continue
        if is_english_name(name):
            culture = country_cultures.get(tag, "???")
            english_names.append((tag, name, culture))

    if not english_names:
        print("All English-sounding names are already in the config!")
        return

    print(f"Found {len(english_names)} English names not yet in config:\n")
    print(f"{'TAG':<8} {'Name':<45} {'Culture'}")
    print("-" * 90)
    for tag, name, culture in english_names:
        print(f"{tag:<8} {name:<45} {culture}")

    print(f"\nAdd these to titles/config.yaml with translations.")


# ---------------------------------------------------------------------------
# List
# ---------------------------------------------------------------------------

def list_titles(cfg: dict):
    """Print summary of all titles and translation status."""
    titles = cfg.get("titles", {})
    languages = cfg.get("languages", [])

    if not titles:
        print("No titles in config yet. Add entries to titles/config.yaml")
        return

    print(f"{'TAG':<8} {'English Name':<35} {'Native':<18} {'Translations'}")
    print("-" * 95)

    for tag, data in titles.items():
        if not isinstance(data, dict):
            continue
        english = data.get("english", "???")
        native = lang_short(data.get("native", "???"))
        translations = data.get("translations", {})
        langs = ", ".join(lang_short(l) for l in translations)
        print(f"{tag:<8} {english:<35} {native:<18} {langs}")

    n_titles = len(titles)
    n_translations = sum(
        len(d.get("translations", {}))
        for d in titles.values()
        if isinstance(d, dict)
    )
    n_languages = len(languages) if languages else 7
    coverage = (n_translations / (n_titles * n_languages) * 100) if n_titles else 0

    print(f"\nTotal: {n_titles} titles, {n_translations} translations")
    print(f"Coverage: {coverage:.0f}% ({n_translations}/{n_titles * n_languages})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate EU5/Etra fantasy title translations.",
    )
    parser.add_argument(
        "config",
        nargs="?",
        default=None,
        help="Path to title translations YAML config",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List all titles and their translation status",
    )
    parser.add_argument(
        "--audit",
        action="store_true",
        help="Find English country names not yet in config",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output directory (default: overrides/)",
    )
    args = parser.parse_args()

    # Find config
    config_path = (
        Path(args.config)
        if args.config
        else SCRIPT_DIR / "titles" / "config.yaml"
    )
    if not config_path.is_file():
        print(f"ERROR: Config not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    cfg = load_config(config_path)

    if args.list:
        list_titles(cfg)
        return

    if args.audit:
        audit_titles(cfg)
        return

    # Output to overrides/ (picked up by generate_mod.py --all)
    out_dir = Path(args.output) if args.output else SCRIPT_DIR / "overrides"

    game_rule_dir = out_dir / "main_menu" / "common" / "game_rules"
    custom_loc_dir = out_dir / "in_game" / "common" / "customizable_localization"
    loc_dir = out_dir / "main_menu" / "localization" / "english"

    for d in (game_rule_dir, custom_loc_dir, loc_dir):
        d.mkdir(parents=True, exist_ok=True)

    titles = cfg.get("titles", {})
    has_titles = any(
        isinstance(d, dict) and d.get("translations")
        for d in titles.values()
    )

    # 1. Game rule (always generated — toggle is useful even with 0 translations)
    game_rule_content = generate_game_rule(cfg)
    game_rule_path = game_rule_dir / "etra_title_names.txt"
    with open(game_rule_path, "w", encoding="utf-8-sig") as f:
        f.write(game_rule_content)
    print(f"  Game rule     -> {game_rule_path}")

    # 2. Localization (always — contains game rule labels)
    loc_content = generate_localization(cfg)
    loc_path = loc_dir / "etra_title_names_l_english.yml"
    with open(loc_path, "w", encoding="utf-8-sig") as f:
        f.write(loc_content)
    print(f"  Localization  -> {loc_path}")

    # 3. Customizable localization (only if there are translations)
    if has_titles:
        custom_loc_content = generate_custom_loc(cfg)
        custom_loc_path = custom_loc_dir / "etra_title_names.txt"
        with open(custom_loc_path, "w", encoding="utf-8-sig") as f:
            f.write(custom_loc_content)
        print(f"  Custom loc    -> {custom_loc_path}")

    # Stats
    n_titles = sum(
        1 for d in titles.values()
        if isinstance(d, dict) and d.get("translations")
    )
    n_translations = sum(
        len(d.get("translations", {}))
        for d in titles.values()
        if isinstance(d, dict)
    )
    print(f"\nDone. {n_titles} titles, {n_translations} translations.")
    if not has_titles:
        print("No translations yet — add entries to titles/config.yaml")
        print("Run: python generate_titles.py --audit  (find English names to translate)")


if __name__ == "__main__":
    main()
