#!/usr/bin/env python3
"""
Generate EU5/Etra fantasy title translations with game rule toggle.

Reads title translations from YAML config and generates:
  1. Game rule file (pre-game toggle: English / Fantasy)
  2. Customizable localization (dynamic per ruler culture)
  3. Localization YML (all translated names)

Output goes to overrides/ so generate_mod.py --all picks it up automatically.

Usage:
    python generate_titles.py                    # generate from titles/config.yaml
    python generate_titles.py titles/custom.yaml # use specific config
    python generate_titles.py --list             # show translation status
    python generate_titles.py --audit            # find English names needing translation

Requires: PyYAML (pip install pyyaml)
"""
import argparse
import re
import sys
from pathlib import Path

import yaml


SCRIPT_DIR = Path(__file__).resolve().parent

# Countries file from the Etra mod (for --audit)
ETRA_MOD = Path(r"C:\Program Files (x86)\Steam\steamapps\workshop\content\3450310\3619896881")
COUNTRY_NAMES_FILE = ETRA_MOD / "main_menu" / "localization" / "english" / "etra_country_names_l_english.yml"
COUNTRY_DEFS_FILE = ETRA_MOD / "in_game" / "setup" / "countries" / "_default.txt"


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config(path: Path) -> dict:
    """Load and validate title translation config."""
    with open(path, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    if not cfg.get("titles"):
        cfg["titles"] = {}

    # Validate translations
    for tag, data in cfg.get("titles", {}).items():
        if not isinstance(data, dict):
            print(f"WARNING: Invalid entry for {tag}, skipping", file=sys.stderr)
            continue
        if "translations" not in data or not data["translations"]:
            print(f"WARNING: {tag} has no translations", file=sys.stderr)

    return cfg


# ---------------------------------------------------------------------------
# Generator: Game Rule
# ---------------------------------------------------------------------------

def generate_game_rule(cfg: dict) -> str:
    """Generate game_rules .txt content."""
    gr = cfg.get("game_rule", {})
    key = gr.get("key", "etra_title_names")
    default = gr.get("default", "fantasy")
    default_setting = f"etra_names_{default}"

    lines = [
        "# Etra: Names & Cultures — Title name language toggle",
        "# Generated by generate_titles.py",
        "#",
        "# When set to Fantasy Languages, country names display in the",
        "# ruler's culture language instead of English.",
        "",
        f"{key} = {{",
        f"\tdefault = {default_setting}",
        "",
        "\tetra_names_english = {",
        "\t\tflag = etra_names_english",
        "\t\tflag = flavour_rule",
        "\t}",
        "",
        "\tetra_names_fantasy = {",
        "\t\tflag = etra_names_fantasy",
        "\t\tflag = flavour_rule",
        "\t}",
        "}",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: Country Name Construction Override
# ---------------------------------------------------------------------------

# Path to Etra mod's country_name_construction.txt (source to copy + extend)
ETRA_COUNTRY_NAME_CONSTRUCTION = (
    ETRA_MOD / "in_game" / "common" / "customizable_localization"
    / "country_name_construction.txt"
)


def generate_name_construction(cfg: dict) -> str:
    """Override country_name_construction for fantasy language constructions.

    Copies Etra's original file but inserts per-language construction
    templates as the FIRST checks. When game rule = fantasy and ruler
    speaks a fantasy language, the country name uses the appropriate
    fantasy construction (e.g., "$RANK$ de $NAME$" for Ardrainic).
    Falls through to Etra's normal logic otherwise.
    """
    ruler_titles = cfg.get("ruler_titles", {})
    constructions = cfg.get("constructions", {})

    if not ruler_titles or not constructions:
        return ""

    # Read Etra's original file
    if not ETRA_COUNTRY_NAME_CONSTRUCTION.exists():
        print(
            f"WARNING: Cannot find Etra country_name_construction at "
            f"{ETRA_COUNTRY_NAME_CONSTRUCTION}",
            file=sys.stderr,
        )
        return ""

    with open(ETRA_COUNTRY_NAME_CONSTRUCTION, encoding="utf-8-sig") as f:
        original = f.read()

    # Build construction entries
    block_lines = [
        "\t# Etra: Names & Cultures — Fantasy country name constructions",
        "",
    ]

    # 1. Translated titles: just $NAME$ (names are already complete proper nouns)
    titles = cfg.get("titles", {})
    tags = [
        tag for tag, data in titles.items()
        if isinstance(data, dict) and data.get("translations")
    ]
    if tags:
        tag_lines = "\n".join(f"\t\t\t\ttag = {t}" for t in tags)
        block_lines.extend([
            "\t# Translated titles — show just $NAME$ (already complete)",
            "\ttext = {",
            "\t\tlocalization_key = country_name_construction_name",
            "\t\ttrigger = {",
            "\t\t\thas_game_rule = etra_names_fantasy",
            "\t\t\tOR = {",
            tag_lines,
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "",
        ])

    # 2. Per-language construction for all other countries
    for lang_name, dialects_list in ruler_titles.items():
        if lang_name not in constructions:
            continue

        loc_key = f"etra_construction_{lang_name}"
        block_lines.append(f"\t# --- {lang_name.upper()} ---")

        for d in dialects_list:
            trigger_type = d.get("trigger", "language")
            trigger_id = d["id"]
            also_matches = d.get("also_matches", [])

            # All IDs to create entries for (main + also_matches)
            all_ids = [(trigger_id, trigger_type)]
            for extra_id in also_matches:
                all_ids.append((extra_id, "language"))

            for tid, ttype in all_ids:
                if ttype == "culture":
                    ruler_line = f"\t\t\truler ?= {{ culture = culture:{tid} }}"
                else:
                    ruler_line = (
                        f"\t\t\truler ?= {{ culture.language = language:{tid} }}"
                    )

                block_lines.extend([
                    "\ttext = {",
                    f"\t\tlocalization_key = {loc_key}",
                    "\t\ttrigger = {",
                    "\t\t\thas_game_rule = etra_names_fantasy",
                    "\t\t\tgovernment_type = government_type:monarchy",
                    ruler_line,
                    "\t\t}",
                    "\t}",
                ])
        block_lines.append("")

    fantasy_block = "\n".join(block_lines) + "\n"

    # Insert our block right after "type = country"
    insert_point = original.find("type = country")
    if insert_point == -1:
        print("WARNING: Could not find 'type = country' in construction file",
              file=sys.stderr)
        return ""

    newline = original.find("\n", insert_point)
    result = original[:newline + 1] + fantasy_block + original[newline + 1:]

    return result


# ---------------------------------------------------------------------------
# Generator: Customizable Localization
# ---------------------------------------------------------------------------

def lang_short(lang_id: str) -> str:
    """Convert language_id to short form for loc keys."""
    return lang_id.replace("_language", "")


def generate_custom_loc(cfg: dict) -> str:
    """Generate customizable_localization .txt content.

    For each title with translations, creates a scope that resolves
    the country name based on game rule + ruler culture.

    Resolution order (first match wins):
      1. Fantasy mode + ruler's specific language → that language's name
      2. Fantasy mode + no match → native language name
      3. English fallback
    """
    titles = cfg.get("titles", {})
    if not titles:
        return ""

    lines = [
        "# Etra: Names & Cultures — Dynamic title names",
        "# Generated by generate_titles.py",
        "#",
        "# Resolves country names based on game rule + ruler culture.",
        "# When game rule = Fantasy: uses ruler's culture language.",
        "# When game rule = English: uses base English name.",
        "",
    ]

    for tag, data in titles.items():
        if not isinstance(data, dict):
            continue
        translations = data.get("translations", {})
        native = data.get("native")
        if not translations:
            continue

        english = data.get("english", tag)
        lines.append(f"# {tag}: {english}")
        lines.append(f"{tag} = {{")
        lines.append("\ttype = country")

        # 1. Per-language triggers (most specific)
        for lang_id in translations:
            loc_key = f"{tag}_{lang_short(lang_id)}"
            lines.append("\ttext = {")
            lines.append(f"\t\tlocalization_key = {loc_key}")
            lines.append("\t\ttrigger = {")
            lines.append("\t\t\thas_game_rule = etra_names_fantasy")
            lines.append(f"\t\t\truler ?= {{ culture.language = language:{lang_id} }}")
            lines.append("\t\t}")
            lines.append("\t}")

        # 2. Native fallback (fantasy mode, ruler language not in translations)
        if native:
            native_key = f"{tag}_{lang_short(native)}"
            if native in translations:
                lines.append("\ttext = {")
                lines.append(f"\t\tlocalization_key = {native_key}")
                lines.append("\t\ttrigger = {")
                lines.append("\t\t\thas_game_rule = etra_names_fantasy")
                lines.append("\t\t}")
                lines.append("\t}")
            else:
                # Native language has no translation — use first available
                first_lang = next(iter(translations))
                fallback_key = f"{tag}_{lang_short(first_lang)}"
                lines.append("\ttext = {")
                lines.append(f"\t\tlocalization_key = {fallback_key}")
                lines.append("\t\ttrigger = {")
                lines.append("\t\t\thas_game_rule = etra_names_fantasy")
                lines.append("\t\t}")
                lines.append("\t}")

        # 3. English fallback
        lines.append("\ttext = {")
        lines.append(f"\t\tlocalization_key = {tag}")
        lines.append("\t\tfallback = yes")
        lines.append("\t}")

        lines.append("}")

        # ADJ shortcut: reuses same function with _ADJ suffix on all loc keys
        if data.get("adjectives"):
            lines.append(f'{tag}_ADJ = {{ parent = {tag} suffix = "_ADJ" }}')

        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: Localization YML
# ---------------------------------------------------------------------------

def generate_localization(cfg: dict) -> str:
    """Generate localization .yml content with game rule labels + translations."""
    titles = cfg.get("titles", {})
    gr = cfg.get("game_rule", {})
    key = gr.get("key", "etra_title_names")
    desc_en = gr.get("desc_english", "Use English names for countries and titles")
    desc_fantasy = gr.get("desc_fantasy", "Use fantasy language names based on ruler's culture")
    label = gr.get("label", "Etra: Title Names")

    lines = [
        "# Etra: Names & Cultures — Title translation localization",
        "# Generated by generate_titles.py",
        "",
        "l_english:",
        "",
        " # --- GAME RULE ---",
        f' rule_{key}: "{label}"',
        f' setting_etra_names_english: "English"',
        f' setting_etra_names_english_desc: "{desc_en}"',
        f' setting_etra_names_fantasy: "Fantasy Languages"',
        f' setting_etra_names_fantasy_desc: "{desc_fantasy}"',
    ]

    if not titles:
        return "\n".join(lines) + "\n"

    lines.append("")
    lines.append(" # --- TITLE TRANSLATIONS ---")

    for tag, data in titles.items():
        if not isinstance(data, dict):
            continue
        translations = data.get("translations", {})
        english = data.get("english", tag)
        if not translations:
            continue

        lines.append(f" # {tag}: {english}")
        for lang_id, translated_name in translations.items():
            loc_key = f"{tag}_{lang_short(lang_id)}"
            # Escape quotes in names
            safe_name = translated_name.replace('"', '\\"')
            lines.append(f' {loc_key}: "{safe_name}"')

        # ADJ localization keys (for $ADJ$ $RANK$ construction)
        adjectives = data.get("adjectives", {})
        if adjectives:
            for lang_id, adj_name in adjectives.items():
                loc_key = f"{tag}_{lang_short(lang_id)}_ADJ"
                safe_adj = adj_name.replace('"', '\\"')
                lines.append(f' {loc_key}: "{safe_adj}"')
            # Native fallback ADJ
            native = data.get("native")
            if native and native in adjectives:
                native_adj_key = f"{tag}_{lang_short(native)}_ADJ"
                # Already added above, but we need the bare fallback key
                # TAG_ADJ fallback is handled by parent = TAG suffix = "_ADJ"
                # which appends _ADJ to the fallback loc key TAG → TAG_ADJ
                # TAG_ADJ is already defined by Etra mod as the English adjective

        lines.append("")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: Ruler Titles (Customizable Localization)
# ---------------------------------------------------------------------------

RANKS = ["empire", "kingdom", "duchy", "county"]
RANK_CHECKS = {
    "empire": "country_rank_is_empire",
    "kingdom": "country_rank_is_kingdom",
    "duchy": "country_rank_is_duchy",
    "county": "country_rank_is_county",
}
RANK_DISPLAY = {
    "empire": "Empire",
    "kingdom": "Kingdom",
    "duchy": "Duchy",
    "county": "County",
}


def ruler_loc_key(dialect_name: str, rank: str) -> str:
    """Build loc key for a ruler title entry."""
    slug = dialect_name.lower().replace(" ", "_")
    return f"etra_rank_{rank}_{slug}"


def generate_ruler_titles_custom_loc(cfg: dict) -> str:
    """Generate country_flavor entries for fantasy ruler titles.

    Creates a country_flavor block with per-dialect triggers.
    Specific dialect entries come first, fallback (language-level) entries
    come last so first-match gives the most specific result.
    """
    ruler_titles = cfg.get("ruler_titles", {})
    if not ruler_titles:
        return ""

    lines = [
        "# Etra: Names & Cultures — Fantasy ruler titles (Monarchy)",
        "# Generated by generate_titles.py",
        "#",
        "# When game rule = Fantasy Languages and government = Monarchy,",
        "# ruler titles (Emperor/King/Duke/Count) display in the",
        "# ruler's culture/dialect language.",
        "#",
        "# Entries are added to country_flavor and evaluated before",
        "# the base game's default entries (file loads first via 00_ prefix).",
        "",
        "country_flavor = {",
        "\ttype = country",
        "",
    ]

    # Collect entries separated by specificity
    specific = []
    fallback = []

    for lang_name, dialects_list in ruler_titles.items():
        for d in dialects_list:
            is_fb = d.get("fallback", False)
            target = fallback if is_fb else specific
            trigger_type = d.get("trigger", "language")
            trigger_id = d["id"]
            dialect_name = d["dialect"]
            also_matches = d.get("also_matches", [])

            for rank in RANKS:
                titles = d.get(rank)
                if not titles:
                    continue

                loc_key = ruler_loc_key(dialect_name, rank)

                # Main entry
                target.append({
                    "loc_key": loc_key,
                    "rank": rank,
                    "trigger_id": trigger_id,
                    "trigger_type": trigger_type,
                    "dialect": dialect_name,
                    "lang": lang_name,
                })

                # Extra entries for also_matches (same loc key, different trigger)
                for extra_id in also_matches:
                    target.append({
                        "loc_key": loc_key,
                        "rank": rank,
                        "trigger_id": extra_id,
                        "trigger_type": "language",
                        "dialect": dialect_name,
                        "lang": lang_name,
                        "extra": True,
                    })

    def write_entry(entry):
        rank_check = RANK_CHECKS[entry["rank"]]
        comment = f"\t# {entry['lang'].title()} — {entry['dialect']}"
        if entry.get("extra"):
            comment += f" (also: {entry['trigger_id']})"
        lines.append(comment)
        lines.append("\ttext = {")
        lines.append(f"\t\tlocalization_key = {entry['loc_key']}")
        lines.append("\t\ttrigger = {")
        lines.append("\t\t\thas_game_rule = etra_names_fantasy")
        lines.append(f"\t\t\t{rank_check} = yes")
        lines.append("\t\t\tgovernment_type = government_type:monarchy")
        if entry["trigger_type"] == "culture":
            lines.append(
                f"\t\t\truler ?= {{ culture = culture:{entry['trigger_id']} }}"
            )
        else:
            lines.append(
                f"\t\t\truler ?= {{ culture.language = language:{entry['trigger_id']} }}"
            )
        lines.append("\t\t}")
        lines.append("\t}")

    # Write specific entries first (most specific triggers)
    if specific:
        lines.append("\t# === SPECIFIC DIALECT ENTRIES ===")
        lines.append("")
        current_lang = None
        for entry in specific:
            if entry["lang"] != current_lang:
                if current_lang is not None:
                    lines.append("")
                current_lang = entry["lang"]
                lines.append(f"\t# --- {current_lang.upper()} ---")
            write_entry(entry)
        lines.append("")

    # Write fallback entries (language-level, less specific)
    if fallback:
        lines.append("\t# === FALLBACK ENTRIES (language-level) ===")
        lines.append("")
        for entry in fallback:
            write_entry(entry)
        lines.append("")

    lines.append("}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Generator: Ruler Titles (Localization)
# ---------------------------------------------------------------------------

def generate_ruler_titles_loc(cfg: dict) -> str:
    """Generate localization entries for ruler titles + construction templates."""
    ruler_titles = cfg.get("ruler_titles", {})
    constructions = cfg.get("constructions", {})
    if not ruler_titles:
        return ""

    lines = ["", " # --- RULER TITLES ---"]
    seen = set()

    for lang_name, dialects_list in ruler_titles.items():
        lines.append(f" # {lang_name.upper()}")
        # Get fantasy polity names for this language (from constructions)
        polity_names = constructions.get(lang_name, {}).get("ranks", {})

        for d in dialects_list:
            dialect = d["dialect"]
            for rank in RANKS:
                titles = d.get(rank)
                if not titles:
                    continue

                loc_key = ruler_loc_key(dialect, rank)
                if loc_key in seen:
                    continue
                seen.add(loc_key)

                male, female = titles
                # Use fantasy polity name if available, else English
                polity = polity_names.get(rank, RANK_DISPLAY[rank])
                lines.append(f' {loc_key}: "{polity}"')
                lines.append(f' {loc_key}_ruler_male: "{male}"')
                lines.append(f' {loc_key}_ruler_female: "{female}"')
        lines.append("")

    # Construction template loc keys
    if constructions:
        lines.append(" # --- CONSTRUCTION TEMPLATES ---")
        for lang_name, cons in constructions.items():
            template = cons.get("template", "$RANK$ of $NAME$")
            map_template = cons.get("map_template", "$NAME$")
            loc_key = f"etra_construction_{lang_name}"
            lines.append(f' {loc_key}: "{template}"')
            lines.append(f' {loc_key}_map: "{map_template}"')
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Audit: find English names needing translation
# ---------------------------------------------------------------------------

def parse_country_names(path: Path) -> dict[str, str]:
    """Parse etra_country_names_l_english.yml → {tag: name}."""
    names = {}
    if not path.exists():
        return names
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or line.startswith("l_english"):
                continue
            # Match: TAG: "Name" or TAG:0 "Name"
            m = re.match(r'^\s*(\w+?)(?::\d+)?\s*:\s*"(.+?)"', line)
            if m:
                tag, name = m.group(1), m.group(2)
                if not tag.endswith("_ADJ"):
                    names[tag] = name
    return names


def parse_country_cultures(path: Path) -> dict[str, str]:
    """Parse _default.txt → {tag: culture_definition} (line-by-line)."""
    cultures = {}
    if not path.exists():
        return cultures
    current_tag = None
    with open(path, encoding="utf-8-sig") as f:
        for line in f:
            m = re.match(r'^(\w+)\s*=\s*\{', line)
            if m:
                current_tag = m.group(1)
            cm = re.search(r'culture_definition\s*=\s*(\w+)', line)
            if cm and current_tag:
                cultures[current_tag] = cm.group(1)
    return cultures


def is_english_name(name: str) -> bool:
    """Heuristic: name contains English words (the, of, and, etc.)."""
    english_markers = [
        "The ", " the ", " of ", " and ", " in ",
        "Order", "Watch", "Daughters", "Sons", "Eagles",
        "Warriors", "Lions", "Sentinels", "Preservers",
        "Path", "Temple", "School", "Judge", "Fist",
        "Star", "Peak", "Bear", "Hawk", "Bell",
        "Crown", "Pale ", "Silent", "Radiant", "Exalted",
        "Little ", "Blue", "Green", "Drunken", "Final",
        "Ashes", "Heaven", "Virtuous", "Autumn",
    ]
    return any(marker in name for marker in english_markers)


def audit_titles(cfg: dict):
    """Find country names that look English and need translation."""
    country_names = parse_country_names(COUNTRY_NAMES_FILE)
    country_cultures = parse_country_cultures(COUNTRY_DEFS_FILE)
    existing = set(cfg.get("titles", {}).keys())

    if not country_names:
        print("ERROR: Could not read country names from Etra mod.", file=sys.stderr)
        print(f"  Expected: {COUNTRY_NAMES_FILE}", file=sys.stderr)
        return

    english_names = []
    for tag, name in sorted(country_names.items()):
        if tag in existing:
            continue
        if is_english_name(name):
            culture = country_cultures.get(tag, "???")
            english_names.append((tag, name, culture))

    if not english_names:
        print("All English-sounding names are already in the config!")
        return

    print(f"Found {len(english_names)} English names not yet in config:\n")
    print(f"{'TAG':<8} {'Name':<45} {'Culture'}")
    print("-" * 90)
    for tag, name, culture in english_names:
        print(f"{tag:<8} {name:<45} {culture}")

    print(f"\nAdd these to titles/config.yaml with translations.")


# ---------------------------------------------------------------------------
# List
# ---------------------------------------------------------------------------

def list_titles(cfg: dict):
    """Print summary of all titles and translation status."""
    titles = cfg.get("titles", {})
    languages = cfg.get("languages", [])

    if not titles:
        print("No titles in config yet. Add entries to titles/config.yaml")
        return

    print(f"{'TAG':<8} {'English Name':<35} {'Native':<18} {'Translations'}")
    print("-" * 95)

    for tag, data in titles.items():
        if not isinstance(data, dict):
            continue
        english = data.get("english", "???")
        native = lang_short(data.get("native", "???"))
        translations = data.get("translations", {})
        langs = ", ".join(lang_short(l) for l in translations)
        print(f"{tag:<8} {english:<35} {native:<18} {langs}")

    n_titles = len(titles)
    n_translations = sum(
        len(d.get("translations", {}))
        for d in titles.values()
        if isinstance(d, dict)
    )
    n_languages = len(languages) if languages else 7
    coverage = (n_translations / (n_titles * n_languages) * 100) if n_titles else 0

    print(f"\nTotal: {n_titles} titles, {n_translations} translations")
    print(f"Coverage: {coverage:.0f}% ({n_translations}/{n_titles * n_languages})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate EU5/Etra fantasy title translations.",
    )
    parser.add_argument(
        "config",
        nargs="?",
        default=None,
        help="Path to title translations YAML config",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List all titles and their translation status",
    )
    parser.add_argument(
        "--audit",
        action="store_true",
        help="Find English country names not yet in config",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Output directory (default: overrides/)",
    )
    args = parser.parse_args()

    # Find config
    config_path = (
        Path(args.config)
        if args.config
        else SCRIPT_DIR / "titles" / "config.yaml"
    )
    if not config_path.is_file():
        print(f"ERROR: Config not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    cfg = load_config(config_path)

    if args.list:
        list_titles(cfg)
        return

    if args.audit:
        audit_titles(cfg)
        return

    # Output to overrides/ (picked up by generate_mod.py --all)
    out_dir = Path(args.output) if args.output else SCRIPT_DIR / "overrides"

    game_rule_dir = out_dir / "main_menu" / "common" / "game_rules"
    custom_loc_dir = out_dir / "in_game" / "common" / "customizable_localization"
    loc_dir = out_dir / "main_menu" / "localization" / "english"

    for d in (game_rule_dir, custom_loc_dir, loc_dir):
        d.mkdir(parents=True, exist_ok=True)

    titles = cfg.get("titles", {})
    has_titles = any(
        isinstance(d, dict) and d.get("translations")
        for d in titles.values()
    )

    # 1. Game rule (always generated — toggle is useful even with 0 translations)
    game_rule_content = generate_game_rule(cfg)
    game_rule_path = game_rule_dir / "etra_title_names.txt"
    with open(game_rule_path, "w", encoding="utf-8-sig") as f:
        f.write(game_rule_content)
    print(f"  Game rule     -> {game_rule_path}")

    # 2. Localization (always — contains game rule labels + ruler titles)
    loc_content = generate_localization(cfg)
    ruler_loc = generate_ruler_titles_loc(cfg)
    if ruler_loc:
        loc_content = loc_content.rstrip("\n") + "\n" + ruler_loc + "\n"
    loc_path = loc_dir / "etra_title_names_l_english.yml"
    with open(loc_path, "w", encoding="utf-8-sig") as f:
        f.write(loc_content)
    print(f"  Localization  -> {loc_path}")

    # 3. Customizable localization — country names (only if there are translations)
    if has_titles:
        custom_loc_content = generate_custom_loc(cfg)
        custom_loc_path = custom_loc_dir / "etra_title_names.txt"
        with open(custom_loc_path, "w", encoding="utf-8-sig") as f:
            f.write(custom_loc_content)
        print(f"  Custom loc    -> {custom_loc_path}")

    # 4. Country name construction override (forces $NAME$ for our titles)
    if has_titles:
        construction_content = generate_name_construction(cfg)
        if construction_content:
            construction_path = custom_loc_dir / "country_name_construction.txt"
            with open(construction_path, "w", encoding="utf-8-sig") as f:
                f.write(construction_content)
            print(f"  Construction  -> {construction_path}")

    # 5. Customizable localization — ruler titles
    ruler_titles = cfg.get("ruler_titles", {})
    ruler_custom_loc = generate_ruler_titles_custom_loc(cfg)
    if ruler_custom_loc:
        ruler_path = custom_loc_dir / "00_etra_ruler_titles.txt"
        with open(ruler_path, "w", encoding="utf-8-sig") as f:
            f.write(ruler_custom_loc)
        print(f"  Ruler titles  -> {ruler_path}")

    # Stats
    n_titles = sum(
        1 for d in titles.values()
        if isinstance(d, dict) and d.get("translations")
    )
    n_translations = sum(
        len(d.get("translations", {}))
        for d in titles.values()
        if isinstance(d, dict)
    )
    # Ruler title stats
    n_ruler_dialects = sum(len(dl) for dl in ruler_titles.values())
    n_ruler_entries = sum(
        sum(1 for r in RANKS if d.get(r))
        for dl in ruler_titles.values()
        for d in dl
    )
    print(f"\nDone. {n_titles} country names, {n_translations} translations.")
    print(f"      {n_ruler_dialects} ruler dialects, {n_ruler_entries} rank entries.")
    if not has_titles and not ruler_titles:
        print("No translations yet — add entries to titles/config.yaml")
        print("Run: python generate_titles.py --audit  (find English names to translate)")


if __name__ == "__main__":
    main()
